---
- hosts: all
  become: true 
  tasks:
  - name: Install basic packages
    yum: name={{ item }} state=present 
    with_items:
    - epel-release
    - htop
    - git
    - ntp
    - syslog
    - ncdu
    - abrt-cli 
    - deltarpm
    - vim 
    - curl 
    - tar 
    - wget 
    - unzip 
  - name: remove package
    yum: name={{ item }} state=absent
    with_items:
    - chrony
