---
- hosts: all
  become: true
  tasks:
  
  - name: add user 
    user:
     name: johnd
     comment: "John Doe"
     uid: 1040
#     group: johnd
  - name: Set authorized key took from file
    command: > 
      mkdir /home/johnd/.ssh
      echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDzvJu3oJu9tSLtFhzk/8t1pKqVk3qSshFr76A6VUY5iO3t3kOgRxJNrQBI0Uz2q0S+81z83HE3PrJkymcRg0bZ79FDd3ry7NU/wDDqrDSjs455rdlrfC9tOareJMJNNwbD+D5t2dp3zZuHCovsC161oDPa/vVdZUyidAYj64zbsP92/2YlOSfzy+y6OktyGNTc2A5c9iCMf1Xgs9DLgdgX4siPM1MmF53+xAb3EHV030dupgBGwMxo1QjrJVliuzb8rVdtHQvNVC/xVrs+bSdBlfAQO0IKPO/vu87Hsm345JA3o47woVIwEd8pD1JAADOHu/HVXYGVzHPZH+PXvg/AqSEESA6d1bxVEk8jHGCXZpWODVxFdt57Hv6wmQ0/d1Nn7u7BnaqXYwj4ORE2rBIgZo52uB/o00OlOsE3wVEg0bxKjWokh4RL53aZnKreoTawQWMSFbDJ0da0rLg5bJMbMT+lqJo8a2cES87buUVs6L+b+tWU5Ep9YhsAXTL2RQAqSoyJ+jNbTY3a/FUxA1XcGLq7LsLEaRYm4fC+4Wh00bjF0d3+55LTwWVnMP1eXE8DvlaX7OZX4GKRdFX+iOKc6jQoE3VewuHS33H4/7AnTCJDGB+9WdoKad9dBqGCW+xtdNqDfEB346WjfVuufdLfmnwH8HEI/RoZCo5K42+Rw== greenberg.charles.h@gmail.com' > /home/charles/.ssh/authorized_keys

